Mid_Project/Controllers/BusController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Mid_Project.Data;
using Mid_Project.Models;

namespace Mid_Project.Controllers
{
    public class BusController : Controller
    {

        private SystemDbContext _context;

        public BusController(SystemDbContext context)
        {
            this._context = context;
        }
        public IActionResult Index()
        {

            return View(_context.buss.ToList());
        }



        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.buss == null)
            {
                return NotFound();
            }

            var bus = _context.buss
                .FirstOrDefault(m => m.bus_Id == id);
            if (bus == null)
            {
                return NotFound();
            }

            return View(bus);
        }

        public IActionResult Create()
        {
            ViewBag.BusTrip = _context.trip.ToList();
            return View();
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection form)
        {
            int adminID = (int)HttpContext.Session.GetInt32("adminID");

            string CaptainName = form["captin_Name"];
            int Seats = int.Parse(form["number_of_seats"]);

            Buss bus = new Buss();
            bus.captin_Name = CaptainName;
            bus.number_of_seats = Seats;
            bus.admin = _context.admin.Find(adminID);

            _context.buss.Add(bus);
            _context.SaveChanges();

            return RedirectToAction("Index");

        }


        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.BusTrip = _context.trip.ToList();

            if (id == null || _context.buss == null)
            {
                return NotFound();
            }
            var players = await _context.buss.FindAsync(id);
            if (players == null)
            {
                return NotFound();
            }
            return View(players);
        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(IFormCollection form)
        {
            string CaptainName = form["captin_Name"];
            int Seats = int.Parse(form["number_of_seats"]);
            int id = int.Parse(form["bus_Id"]);

            Buss bus = _context.buss.Find(id);
            bus.captin_Name = CaptainName;
            bus.number_of_seats = Seats;

            


            _context.buss.Update(bus);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }



        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.buss == null)
            {
                return NotFound();
            }

            var bus = await _context.buss
                .FirstOrDefaultAsync(m => m.bus_Id == id);
            if (bus == null)
            {
                return NotFound();
            }

            return View(bus);
        }


        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.buss == null)
            {
                return Problem("Entity set 'SystemDbContext.bus'  is null.");
            }
            var bus = await _context.buss.FindAsync(id);
            if (bus != null)
            {
                _context.buss.Remove(bus);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BusExists(int id)
        {
            return (_context.buss?.Any(e => e.bus_Id == id)).GetValueOrDefault();
        }
    }
}

Mid_Project/Controllers/Trip_BussController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Mid_Project.Data;
using Mid_Project.Models;

namespace Mid_Project.Controllers
{
    public class Trip_BussController : Controller
    {
        private readonly SystemDbContext _context;

        public Trip_BussController(SystemDbContext context)
        {
            _context = context;
        }

        // GET: Trip_Buss
        public  IActionResult Index()
        {
            return View(_context.trip_buss.Include(tb => tb.trip).Include(tb => tb.buss).ToList());
            
        }

        // GET: Trip_Buss/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            Trip_Buss tripBuss = _context.trip_buss
              .Include(tb => tb.trip) // Include the Trip navigation property
              .Include(tb => tb.buss) // Include the Buss navigation property
              .FirstOrDefault(tb => tb.ID == id);
            return View(tripBuss);
        }

        // GET: Trip_Buss/Create
        public IActionResult Create()
        {
            ViewBag.Buss = _context.buss.ToList();
            ViewBag.Trip = _context.trip.ToList();
            return View();
        }

        // POST: Trip_Buss/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public IActionResult Create(int trip, int bus)
        {
            Trip_Buss tp = new Trip_Buss();
            tp.trip = _context.trip.Find(trip);
            tp.buss = _context.buss.Find(bus);
            _context.trip_buss.Add(tp);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }


        // GET: Trip_Buss/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewBag.Buss = _context.buss.ToList();
            ViewBag.Trip = _context.trip.ToList();
            return View();
        }

        // POST: Trip_Buss/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id,int trip, int bus)
        {

            Trip_Buss tp = _context.trip_buss.Find(id);
            tp.trip = _context.trip.Find(trip);
            tp.buss = _context.buss.Find(bus);
            _context.trip_buss.Update(tp);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        // GET: Trip_Buss/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
                Trip_Buss tripBuss = _context.trip_buss
                .Include(tb => tb.trip) // Include the Trip navigation property
                .Include(tb => tb.buss) // Include the Buss navigation property
                .FirstOrDefault(tb => tb.ID == id);
            return View(tripBuss);
        }

        // POST: Trip_Buss/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.trip_buss == null)
            {
                return Problem("Entity set 'SystemDbContext.trip_buss'  is null.");
            }
            var trip_Buss = await _context.trip_buss.FindAsync(id);
            if (trip_Buss != null)
            {
                _context.trip_buss.Remove(trip_Buss);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Trip_BussExists(int id)
        {
          return (_context.trip_buss?.Any(e => e.ID == id)).GetValueOrDefault();
        }
    }
}

Mid_Project/Views/Admin/Create.cshtml
@model Mid_Project.Models.Trip

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Trip</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="destination" class="control-label"></label>
                <input asp-for="destination" class="form-control" />
                <span asp-validation-for="destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="start_Date" class="control-label"></label>
                <input asp-for="start_Date" class="form-control" />
                <span asp-validation-for="start_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="end_Date" class="control-label"></label>
                <input asp-for="end_Date" class="form-control" />
                <span asp-validation-for="end_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bus_Number" class="control-label"></label>
                <input asp-for="bus_Number" class="form-control" />
                <span asp-validation-for="bus_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Mid_Project/Views/Admin/Delete.cshtml
@model Mid_Project.Models.Trip

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>BusTrip</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.destination)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.destination)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.start_Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.start_Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.end_Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.end_Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.bus_Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.bus_Number)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="trip_Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Mid_Project/Views/Admin/Details.cshtml
@model Mid_Project.Models.Trip

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>BusTrip</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.destination)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.destination)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.start_Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.start_Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.end_Date)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.end_Date)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.bus_Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.bus_Number)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.trip_Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Mid_Project/Views/Admin/Edit.cshtml
@model Mid_Project.Models.Trip

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>BusTrip</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="trip_Id" />
            <div class="form-group">
                <label asp-for="destination" class="control-label"></label>
                <input asp-for="destination" class="form-control" />
                <span asp-validation-for="destination" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="start_Date" class="control-label"></label>
                <input asp-for="start_Date" class="form-control" />
                <span asp-validation-for="start_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="end_Date" class="control-label"></label>
                <input asp-for="end_Date" class="form-control" />
                <span asp-validation-for="end_Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="bus_Number" class="control-label"></label>
                <input asp-for="bus_Number" class="form-control" />
                <span asp-validation-for="bus_Number" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Mid_Project/Views/Admin/Index.cshtml
@model IEnumerable<Mid_Project.Models.Trip>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
    <a asp-action="Index" asp-controller="Bus">Go to Bus</a>
    <a asp-action="Index" asp-controller="Trip_Buss">Go to Trip Buss </a>

</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.destination)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.start_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.end_Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.bus_Number)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.destination)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.start_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.end_Date)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.bus_Number)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.trip_Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.trip_Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.trip_Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>